

trainer:
  batch_size: 64
  output_directory: "some_path"
  optimizer:
    - module_name: Adam
      learning_rate: 1e-4
      beta_1: 0.9
      beta_2: 0.999
    - module_name: SGD
      learning_rate: 1e-4

metrics:
  - module_name: Accuracy
    threshold: 0.5
  - module_name: AreaUnderCurve
